name: Deploy Laravel to Server

on:
  push:
    branches:
      - main  # Deploy hanya dari branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.13.206.28 >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa -v mobility@103.13.206.28 "echo Connected!"

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa mobility@103.13.206.28 << 'EOF'
          cd /var/www/laravel &&
          git pull origin main &&
          composer install --no-dev --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan cache:clear &&
          php artisan config:clear &&
          php artisan queue:restart &&
          sudo systemctl restart nginx
          EOF
